include theme_onedark.conf
shell .
include map.conf
confirm_os_window_close 1
allow_remote_control yes
remember_window_size no

initial_window_width 140c
initial_window_height 38c

placement_strategy center
