########################################
# SPLITS
########################################
enabled_layouts splits:split_axis=horizontal
# Horizontal split
# horizontal (atas bawah)
map ctrl+shift+0 launch --location=hsplit --cwd=current

# vertical (kiri kanan)
map ctrl+shift+9 launch --location=vsplit --cwd=current

########################################
# RESIZE SPLITS (IJKL)
########################################


map ctrl+shift+l resize_window narrower 5
map ctrl+shift+j resize_window wider 5
map ctrl+shift+i resize_window taller 5
map ctrl+shift+k resize_window shorter 5

########################################
# MOVE BETWEEN SPLITS
########################################

map ctrl+shift+left neighboring_window left
map ctrl+shift+right neighboring_window right
map ctrl+shift+up neighboring_window up
map ctrl+shift+down neighboring_window down

########################################
# MOVE SPLIT POSITION
########################################

map ctrl+shift+[ move_window backward
map ctrl+shift+] move_window forward
