new_tab Main

enabled_layouts splits:split_axis=horizontal
layout splits

# kiri besar
launch nvim .

# kanan atas
launch --location=vsplit zsh

# fokus ke kanan
focus_matching_window id:2

# kanan bawah
launch --location=hsplit zsh
