########################################
hide_window_decorations yes
window_padding_width 10

font_family      JetBrains Nerd Font
bold_font        true
italic_font      auto
bold_italic_font auto
font_size 12.0
disable_ligatures never

########################################
# CURSOR
########################################

cursor_shape beam
cursor_beam_thickness 2.0
cursor_trail 3
cursor_blink_interval 0.5
cursor_stop_blinking_after 15

shell_integration enabled

########################################
# CURSOR TRAIL / SMOOTH EFFECT
########################################

########################################
# SCROLLING
########################################

smooth_scroll_steps 1.0
wheel_scroll_multiplier 5.0
touch_scroll_multiplier 6.0

scrollback_lines 10000

########################################
# WINDOW
########################################

remember_window_size no
initial_window_width 180c
initial_window_height 45c

resize_draw_strategy scale

########################################
# TRANSPARENCY
########################################

background_opacity 0.60
dynamic_background_opacity yes


########################################
# PERFORMANCE
########################################

repaint_delay 8
input_delay 1
sync_to_monitor yes

########################################
# TAB BAR
########################################

tab_bar_edge top
tab_bar_style powerline

active_tab_font_style bold
inactive_tab_font_style normal

########################################
# COLORS
########################################

foreground #e0def4
background #232136

selection_foreground #e0def4
selection_background #44415a

cursor #56526e
cursor_text_color #e0def4

########################################
# ROSE PINE MOON STYLE
########################################

color0  #393552
color1  #eb6f92
color2  #31748f
color3  #f6c177
color4  #9ccfd8
color5  #c4a7e7
color6  #ebbcba
color7  #e0def4

color8  #6e6a86
color9  #eb6f92
color10 #31748f
color11 #f6c177
color12 #9ccfd8
color13 #c4a7e7
color14 #ebbcba
color15 #e0def4

########################################
# BELL
########################################

enable_audio_bell no
visual_bell_duration 0.0

########################################
# MOUSE
########################################

mouse_hide_wait 1.0
copy_on_select yes

########################################
# LINUX / WAYLAND / X11
########################################

linux_display_server auto

########################################
# FAST OPENGL
########################################

wayland_enable_ime yes

########################################
# ANIMATION FEEL
########################################

confirm_os_window_close 0
placement_strategy center

########################################
# SHELL
########################################
