########################################
hide_window_decorations yes
window_padding_width 10

font_family      JetBrains Nerd Font
bold_font        true
italic_font      auto
bold_italic_font auto
font_size 12.0
disable_ligatures never

########################################
# CURSOR
########################################

cursor_shape beam
cursor_beam_thickness 2.0
cursor_trail 3
cursor_blink_interval 0.5
cursor_stop_blinking_after 15

shell_integration enabled

########################################
# CURSOR TRAIL / SMOOTH EFFECT
########################################

########################################
# SCROLLING
########################################

smooth_scroll_steps 1.0
wheel_scroll_multiplier 5.0
touch_scroll_multiplier 6.0

scrollback_lines 10000

########################################
# WINDOW
########################################

remember_window_size no
initial_window_width 180c
initial_window_height 45c

resize_draw_strategy scale

########################################
# TRANSPARENCY
########################################

background_opacity 0.80
dynamic_background_opacity yes


########################################
# PERFORMANCE
########################################

repaint_delay 8
input_delay 1
sync_to_monitor yes

########################################
# TAB BAR
########################################

tab_bar_edge top
tab_bar_style powerline

active_tab_font_style bold
inactive_tab_font_style normal

########################################
# COLORS
########################################

foreground #abb2bf
background #1e222a

selection_foreground #abb2bf
selection_background #3e4452

cursor #528bff
cursor_text_color #1e222a

########################################
# ONE DARK STYLE
########################################

color0  #1e222a
color1  #e06c75
color2  #98c379
color3  #d19a66
color4  #61afef
color5  #c678dd
color6  #56b6c2
color7  #abb2bf

color8  #545862
color9  #e06c75
color10 #98c379
color11 #d19a66
color12 #61afef
color13 #c678dd
color14 #56b6c2
color15 #ffffff

enable_audio_bell no
visual_bell_duration 0.0


mouse_hide_wait 1.0
copy_on_select yes

########################################
# LINUX / WAYLAND / X11
########################################

linux_display_server auto

########################################
# FAST OPENGL
########################################

wayland_enable_ime yes

########################################
# ANIMATION FEEL
########################################

confirm_os_window_close 0
placement_strategy center

########################################
# SHELL
########################################
